// Sovereign Health Intelligence -- AGPL-3.0 -- https://sovereignhealth.io/

// ============================================================================
//  SOVEREIGN HEALTH INTELLIGENCE
//
//  BLOOD · BIOMARKERS · INSIGHT
//
//  Privacy-first platform for collecting, analyzing, and understanding
//  blood markers and laboratory data.
//
//  Your body is the operating system of your life.
//  Blood is its diagnostic interface.
//
//  Bitcoin introduced Proof of Work.
//  Health needs Proof of Blood.
//
//  Inspired by the principles of sovereignty, self-custody,
//  and the ideas explored in "Brick by Brick":
//  https://www.amazon.de/-/en/Brick-Building-Sovereign-Life-Bitcoin/dp/B0FR42K8R1
//
//  Own your data. Understand your biology. Build health sovereignty.
//
//  https://sovereignhealth.io/
//  AGPL-3.0 -- https://github.com/sovereignbrick/brickos
// ============================================================================

use serde::{Deserialize, Serialize};

pub mod config;
pub mod error;
pub mod handlers;
pub mod middleware;
pub mod models;
pub mod payments;
pub mod services;
pub mod templates;

pub const VERSION: &str = "0.43.0";
pub const SERVICE_NAME: &str = "sovereign-health-backend";

/// Platform database pool (brickos DB -- users, orgs, billing, service accounts).
/// Distinguished from the app pool (health DB) via newtype pattern.
#[derive(Clone)]
pub struct PlatformPool(pub sqlx::PgPool);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthResponse {
    pub status: String,
    pub service: String,
    pub version: String,
    pub timestamp: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checks: Option<HealthChecks>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ai_system: Option<AiSystemInfo>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiSystemInfo {
    pub name: String,
    pub provider: String,
    pub model: String,
    pub classification: String,
    pub purpose: String,
    pub limitations: String,
    pub data_scope: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthChecks {
    pub database: HealthCheckResult,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub platform_database: Option<HealthCheckResult>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthCheckResult {
    pub status: String,
    pub latency_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloResponse {
    pub message: String,
    pub version: String,
}

pub fn configure_routes(cfg: &mut actix_web::web::ServiceConfig) {
    use actix_governor::{Governor, GovernorConfigBuilder};

    // Read governor config from app data (Config struct), fall back to defaults
    let per_second = std::env::var("AUTH_GOVERNOR_PER_SECOND")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(12u64);
    let burst_size = std::env::var("AUTH_GOVERNOR_BURST_SIZE")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(5u32);
    let auth_governor = GovernorConfigBuilder::default()
        .seconds_per_request(per_second)
        .burst_size(burst_size)
        .finish()
        .expect("invalid governor config");

    cfg.route(
        "/health",
        actix_web::web::get().to(handlers::health::health),
    )
    .route(
        "/api/v1/hello",
        actix_web::web::get().to(handlers::health::hello),
    )
    .route(
        "/api/v1/health/metrics",
        actix_web::web::get().to(handlers::health::metrics),
    )
    // Sprint 044 #547: public branding endpoint (no auth required)
    .route(
        "/api/v1/org/branding",
        actix_web::web::get().to(handlers::org_branding::get_branding),
    )
    .route(
        "/early-access",
        actix_web::web::post().to(handlers::early_access::submit),
    )
    .service(
        actix_web::web::scope("/api/newsletter")
            .route(
                "/subscribe",
                actix_web::web::post().to(handlers::newsletter::subscribe),
            )
            .route(
                "/confirm",
                actix_web::web::get().to(handlers::newsletter::confirm),
            )
            .route(
                "/unsubscribe",
                actix_web::web::post().to(handlers::newsletter::unsubscribe),
            ),
    )
    .route(
        "/api/contact",
        actix_web::web::post().to(handlers::contact::submit),
    )
    // Public tier/feature matrix (no auth)
    .route(
        "/api/tiers/features",
        actix_web::web::get().to(handlers::license::tiers_features),
    )
    // Search (public for Tier 1, authenticated for Tier 2 + user content)
    .service(
        actix_web::web::scope("/api/v1/search")
            .route("", actix_web::web::get().to(handlers::search::search))
            .route(
                "/suggest",
                actix_web::web::get().to(handlers::search::suggest),
            )
            .route(
                "/reindex",
                actix_web::web::post().to(handlers::search::reindex),
            ),
    )
    // Info bar config (public — no auth)
    .route(
        "/api/config/infobar",
        actix_web::web::get().to(handlers::admin_settings::public_infobar),
    )
    // Donation routes (public — no auth)
    .service(
        actix_web::web::scope("/donate")
            .route(
                "/invoice",
                actix_web::web::post().to(handlers::donate::create_donation_invoice),
            )
            .route(
                "/status/{invoice_id}",
                actix_web::web::get().to(handlers::donate::get_donation_status),
            ),
    )
    // Registration status is public and must NOT be rate-limited by the auth governor
    .route(
        "/auth/registration-status",
        actix_web::web::get().to(handlers::auth::registration_status),
    )
    .service(
        actix_web::web::scope("/auth")
            .wrap(Governor::new(&auth_governor))
            .route("/signup", actix_web::web::post().to(handlers::auth::signup))
            .route("/login", actix_web::web::post().to(handlers::auth::login))
            .route(
                "/nostr",
                actix_web::web::post().to(handlers::auth_nostr::nostr_login),
            )
            .route(
                "/verify",
                actix_web::web::get().to(handlers::auth::verify_email),
            )
            .route(
                "/resend-verification",
                actix_web::web::post().to(handlers::auth::resend_verification),
            )
            .route(
                "/forgot-password",
                actix_web::web::post().to(handlers::auth::forgot_password),
            )
            .route(
                "/reset-password",
                actix_web::web::post().to(handlers::auth::reset_password),
            )
            .route(
                "/refresh",
                actix_web::web::post().to(handlers::auth::refresh),
            )
            .route("/me", actix_web::web::get().to(handlers::auth::me))
            // Sprint 040 #484 -- multi-org switcher
            .route(
                "/me/orgs",
                actix_web::web::get().to(handlers::auth::list_my_orgs),
            )
            .route(
                "/unsubscribe",
                actix_web::web::get().to(handlers::auth::unsubscribe),
            )
            .route(
                "/mfa/setup",
                actix_web::web::post().to(handlers::mfa::mfa_setup),
            )
            .route(
                "/mfa/verify-setup",
                actix_web::web::post().to(handlers::mfa::mfa_verify_setup),
            )
            .route(
                "/mfa/disable",
                actix_web::web::post().to(handlers::mfa::mfa_disable),
            )
            .route(
                "/mfa/verify-login",
                actix_web::web::post().to(handlers::mfa::mfa_verify_login),
            )
            .route(
                "/mfa/regenerate-recovery",
                actix_web::web::post().to(handlers::mfa::mfa_regenerate_recovery),
            )
            .route(
                "/mfa/status",
                actix_web::web::get().to(handlers::mfa::mfa_status),
            )
            .route(
                "/change-password",
                actix_web::web::post().to(handlers::mfa::change_password),
            ),
    )
    .service(
        actix_web::web::scope("/measurements")
            .route("", actix_web::web::get().to(handlers::measurements::list))
            .route(
                "",
                actix_web::web::post().to(handlers::measurements::create),
            )
            .route(
                "/filters",
                actix_web::web::get().to(handlers::measurements::filters),
            )
            .route(
                "/{id}",
                actix_web::web::get().to(handlers::measurements::get_one),
            )
            .route(
                "/{id}",
                actix_web::web::put().to(handlers::measurements::update),
            )
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::measurements::delete),
            ),
    )
    .service(
        actix_web::web::scope("/sync")
            .route(
                "/version",
                actix_web::web::get().to(handlers::sync::version),
            )
            .route(
                "/changes",
                actix_web::web::get().to(handlers::sync::changes),
            ),
    )
    .service(
        actix_web::web::scope("/push")
            .route(
                "/vapid-key",
                actix_web::web::get().to(handlers::push::vapid_key),
            )
            .route(
                "/subscribe",
                actix_web::web::post().to(handlers::push::subscribe),
            )
            .route(
                "/unsubscribe",
                actix_web::web::delete().to(handlers::push::unsubscribe),
            ),
    )
    .service(
        actix_web::web::scope("/markers")
            .route("", actix_web::web::get().to(handlers::markers::list))
            .route(
                "/{slug}",
                actix_web::web::get().to(handlers::markers::detail),
            )
            .route(
                "/{slug}/measurements",
                actix_web::web::get().to(handlers::markers::marker_measurements),
            )
            .route(
                "/{slug}/trend",
                actix_web::web::get().to(handlers::markers::marker_trend),
            )
            .route(
                "/{slug}/content",
                actix_web::web::get().to(handlers::markers::marker_content),
            )
            .route(
                "/{slug}/foods",
                actix_web::web::get().to(handlers::markers::marker_foods),
            )
            .route(
                "/{slug}/supplements",
                actix_web::web::get().to(handlers::markers::marker_supplements),
            )
            .route(
                "/{slug}/references",
                actix_web::web::get().to(handlers::markers::marker_references_list),
            ),
    )
    // Sprint 040 #468 part 2a -- active vs preserved markers
    .service(
        actix_web::web::scope("/user-markers")
            .route("", actix_web::web::get().to(handlers::user_markers::list))
            .route(
                "/{slug}/activate",
                actix_web::web::put().to(handlers::user_markers::activate),
            )
            .route(
                "/{slug}/deactivate",
                actix_web::web::put().to(handlers::user_markers::deactivate),
            )
            .route(
                "/swap",
                actix_web::web::post().to(handlers::user_markers::swap),
            ),
    )
    .service(
        actix_web::web::scope("/devices")
            .route("", actix_web::web::get().to(handlers::devices::list))
            .route("", actix_web::web::post().to(handlers::devices::create))
            .route("/{id}", actix_web::web::put().to(handlers::devices::update))
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::devices::delete),
            )
            .route(
                "/{id}/default",
                actix_web::web::post().to(handlers::devices::set_default),
            )
            .route(
                "/{id}/history",
                actix_web::web::get().to(handlers::devices::history),
            ),
    )
    .service(
        actix_web::web::scope("/labs")
            .route("", actix_web::web::get().to(handlers::labs::list))
            .route("", actix_web::web::post().to(handlers::labs::create))
            .route("/{id}", actix_web::web::put().to(handlers::labs::update))
            .route("/{id}", actix_web::web::delete().to(handlers::labs::delete)),
    )
    .route(
        "/calculated-markers",
        actix_web::web::get().to(handlers::trends::calculated_markers),
    )
    .service(
        actix_web::web::scope("/zones")
            .route("", actix_web::web::get().to(handlers::zones::list))
            .route("/{slug}", actix_web::web::get().to(handlers::zones::detail)),
    )
    .service(
        actix_web::web::scope("/settings")
            .route(
                "",
                actix_web::web::get().to(handlers::settings::get_settings),
            )
            .route(
                "/profile",
                actix_web::web::put().to(handlers::settings::update_profile),
            )
            .route(
                "/units",
                actix_web::web::put().to(handlers::settings::update_units),
            )
            .route(
                "/lifestyle",
                actix_web::web::put().to(handlers::settings::update_lifestyle),
            )
            .route(
                "/reference-ranges/bulk",
                actix_web::web::put().to(handlers::settings::update_reference_ranges_bulk),
            )
            .route(
                "/reference-ranges",
                actix_web::web::delete().to(handlers::settings::delete_all_reference_ranges),
            )
            .route(
                "/reference-ranges/{marker_slug}",
                actix_web::web::put().to(handlers::settings::update_reference_range),
            )
            .route(
                "/reference-ranges/{marker_slug}",
                actix_web::web::delete().to(handlers::settings::delete_reference_range),
            )
            .route(
                "/export-all",
                actix_web::web::post().to(handlers::settings::export_all),
            )
            .route(
                "/reset-data",
                actix_web::web::post().to(handlers::settings::reset_data),
            )
            .route(
                "/account",
                actix_web::web::delete().to(handlers::settings::delete_account),
            )
            .route(
                "/anonymous-data",
                actix_web::web::put().to(handlers::settings::update_anonymous_data),
            )
            .route(
                "/consent",
                actix_web::web::get().to(handlers::settings::get_consent),
            )
            .route(
                "/consent",
                actix_web::web::put().to(handlers::settings::update_consent),
            )
            .route(
                "/access-log",
                actix_web::web::get().to(handlers::settings::get_access_log),
            ),
    )
    .route(
        "/export/csv",
        actix_web::web::get().to(handlers::export::export_csv),
    )
    .route(
        "/export/json",
        actix_web::web::get().to(handlers::reports::export_json),
    )
    .service(
        actix_web::web::scope("/reports")
            .route(
                "/health-pdf",
                actix_web::web::post().to(handlers::reports::health_pdf),
            )
            .route(
                "/history",
                actix_web::web::get().to(handlers::reports::report_history),
            )
            .route(
                "/quota",
                actix_web::web::get().to(handlers::reports::report_quota),
            ),
    )
    .service(actix_web::web::scope("/trends").route(
        "/{marker_slug}",
        actix_web::web::get().to(handlers::trends::trends),
    ))
    .service(
        actix_web::web::scope("/license")
            .route("", actix_web::web::get().to(handlers::license::get_license))
            .route(
                "/tiers",
                actix_web::web::get().to(handlers::license::list_tiers),
            )
            .route(
                "/usage",
                actix_web::web::get().to(handlers::license::get_usage),
            )
            .route(
                "/downgrade",
                actix_web::web::put().to(handlers::license::downgrade),
            ),
    )
    // Sprint 044: org owner self-service settings
    .service(
        actix_web::web::scope("/org-settings")
            // General
            .route(
                "/general",
                actix_web::web::get().to(handlers::org_settings::get_general),
            )
            .route(
                "/general",
                actix_web::web::put().to(handlers::org_settings::update_general),
            )
            // Branding
            .route(
                "/branding",
                actix_web::web::get().to(handlers::org_settings::get_branding),
            )
            .route(
                "/branding",
                actix_web::web::put().to(handlers::org_settings::update_branding),
            )
            // Members
            .route(
                "/members",
                actix_web::web::get().to(handlers::org_settings::list_members),
            )
            .route(
                "/members",
                actix_web::web::post().to(handlers::org_settings::invite_member),
            )
            .route(
                "/members/{user_id}/role",
                actix_web::web::put().to(handlers::org_settings::update_member_role),
            )
            .route(
                "/members/{user_id}",
                actix_web::web::delete().to(handlers::org_settings::remove_member),
            )
            // Domains
            .route(
                "/domains",
                actix_web::web::get().to(handlers::org_settings::list_domains),
            )
            // Analytics
            .route(
                "/analytics",
                actix_web::web::get().to(handlers::org_settings::analytics),
            )
            // Apps
            .route(
                "/apps",
                actix_web::web::get().to(handlers::org_settings::list_apps),
            )
            .route(
                "/apps/shi/ai",
                actix_web::web::get().to(handlers::org_settings::get_shi_ai_config),
            )
            .route(
                "/apps/shi/ai",
                actix_web::web::put().to(handlers::org_settings::update_shi_ai_config),
            )
            .route(
                "/apps/shi/email",
                actix_web::web::get().to(handlers::org_settings::get_shi_email_config),
            )
            .route(
                "/apps/shi/email",
                actix_web::web::put().to(handlers::org_settings::update_shi_email_config),
            )
            // Billing
            .route(
                "/billing",
                actix_web::web::get().to(handlers::org_settings::get_billing),
            ),
    )
    // Sprint 044 #553: practitioner dashboard (org members + read-only health data)
    .service(
        actix_web::web::scope("/practitioner")
            .route(
                "/members",
                actix_web::web::get().to(handlers::practitioner::list_members),
            )
            .route(
                "/members/{user_id}/summary",
                actix_web::web::get().to(handlers::practitioner::member_summary),
            ),
    )
    .service(
        actix_web::web::scope("/doctor-chat")
            .route("", actix_web::web::post().to(handlers::doctor_chat::chat))
            .route(
                "/quota",
                actix_web::web::get().to(handlers::doctor_chat::get_quota),
            )
            .route(
                "/conversations",
                actix_web::web::get().to(handlers::doctor_chat::list_conversations),
            )
            .route(
                "/conversations/{id}",
                actix_web::web::get().to(handlers::doctor_chat::get_conversation),
            )
            .route(
                "/conversations/{id}",
                actix_web::web::put().to(handlers::doctor_chat::rename_conversation),
            )
            .route(
                "/conversations/{id}",
                actix_web::web::delete().to(handlers::doctor_chat::delete_conversation),
            )
            .route(
                "/conversations/{id}/rate",
                actix_web::web::post().to(handlers::doctor_chat::rate_message),
            ),
    )
    .service(
        actix_web::web::scope("/measurement-templates")
            .route("", actix_web::web::get().to(handlers::templates::list))
            .route("", actix_web::web::post().to(handlers::templates::create))
            .route(
                "/{id}",
                actix_web::web::put().to(handlers::templates::update),
            )
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::templates::delete),
            )
            .route(
                "/{id}/touch",
                actix_web::web::post().to(handlers::templates::touch),
            ),
    )
    .service(
        actix_web::web::scope("/knowledge")
            .route(
                "/markers/{slug}",
                actix_web::web::get().to(handlers::knowledge::marker_knowledge),
            )
            .route(
                "/markers/{slug}/relations",
                actix_web::web::get().to(handlers::knowledge::marker_relations),
            )
            .route(
                "/protocols/{protocol}",
                actix_web::web::get().to(handlers::knowledge::protocol_effects),
            )
            .route(
                "/search",
                actix_web::web::get().to(handlers::knowledge::knowledge_search),
            )
            .route(
                "/cohort",
                actix_web::web::get().to(handlers::knowledge::cohort_stub),
            ),
    )
    .service(
        actix_web::web::scope("/medications")
            .route(
                "/catalog",
                actix_web::web::get().to(handlers::medications::catalog),
            )
            .route("", actix_web::web::get().to(handlers::medications::list))
            .route("", actix_web::web::post().to(handlers::medications::create))
            .route(
                "/interactions",
                actix_web::web::get().to(handlers::medications::interactions),
            )
            .route(
                "/{id}",
                actix_web::web::put().to(handlers::medications::update),
            )
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::medications::delete),
            )
            .route(
                "/{id}/marker-effects",
                actix_web::web::get().to(handlers::medications::marker_effects),
            ),
    )
    .service(
        actix_web::web::scope("/user-medications")
            .route(
                "",
                actix_web::web::get().to(handlers::user_medications::list),
            )
            .route(
                "",
                actix_web::web::post().to(handlers::user_medications::create),
            )
            .route(
                "/active-context",
                actix_web::web::get().to(handlers::user_medications::active_context),
            )
            .route(
                "/{id}",
                actix_web::web::get().to(handlers::user_medications::get_one),
            )
            .route(
                "/{id}",
                actix_web::web::put().to(handlers::user_medications::update),
            )
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::user_medications::archive),
            )
            .route(
                "/{id}/restore",
                actix_web::web::put().to(handlers::user_medications::restore),
            ),
    )
    .service(
        actix_web::web::scope("/influence-factors")
            .route(
                "",
                actix_web::web::get().to(handlers::influence_factors::list),
            )
            .route(
                "",
                actix_web::web::post().to(handlers::influence_factors::create),
            )
            .route(
                "/{id}",
                actix_web::web::get().to(handlers::influence_factors::get_one),
            )
            .route(
                "/{id}",
                actix_web::web::put().to(handlers::influence_factors::update),
            )
            .route(
                "/{id}",
                actix_web::web::delete().to(handlers::influence_factors::archive),
            )
            .route(
                "/{id}/restore",
                actix_web::web::put().to(handlers::influence_factors::restore),
            ),
    )
    .service(
        actix_web::web::scope("/import")
            .route(
                "/upload",
                actix_web::web::post().to(handlers::import::upload),
            )
            .route(
                "/upload-medication",
                actix_web::web::post().to(handlers::import::upload_medication),
            )
            .route(
                "/{id}/confirm",
                actix_web::web::post().to(handlers::import::confirm),
            )
            .route(
                "/{id}/confirm-medications",
                actix_web::web::post().to(handlers::import::confirm_medications),
            )
            .route(
                "/upload-measurements",
                actix_web::web::post().to(handlers::import::upload_measurements),
            )
            .route(
                "/confirm-measurements",
                actix_web::web::post().to(handlers::import::confirm_measurements),
            )
            .route(
                "/history",
                actix_web::web::get().to(handlers::import::history),
            )
            .route(
                "/sessions/{id}/rollback",
                actix_web::web::delete().to(handlers::import::rollback_import),
            )
            .route(
                "/{id}",
                actix_web::web::get().to(handlers::import::get_session),
            ),
    )
    .service(
        actix_web::web::scope("/demo")
            .route(
                "/zones",
                actix_web::web::get().to(handlers::demo::demo_zones),
            )
            .route(
                "/zones/{slug}",
                actix_web::web::get().to(handlers::demo::demo_zone_detail),
            )
            .route(
                "/measurements",
                actix_web::web::get().to(handlers::demo::demo_measurements),
            )
            .route(
                "/measurements/filters",
                actix_web::web::get().to(handlers::demo::demo_measurements_filters),
            )
            .route(
                "/trends/{marker_slug}",
                actix_web::web::get().to(handlers::demo::demo_trends),
            )
            .route(
                "/markers/{slug}",
                actix_web::web::get().to(handlers::markers::demo_detail),
            )
            .route(
                "/markers/{slug}/measurements",
                actix_web::web::get().to(handlers::markers::demo_marker_measurements),
            )
            .route(
                "/markers/{slug}/trend",
                actix_web::web::get().to(handlers::markers::demo_marker_trend),
            )
            .route(
                "/markers/{slug}/content",
                actix_web::web::get().to(handlers::markers::demo_marker_content),
            )
            .route(
                "/markers/{slug}/foods",
                actix_web::web::get().to(handlers::markers::demo_marker_foods),
            )
            .route(
                "/markers/{slug}/supplements",
                actix_web::web::get().to(handlers::markers::demo_marker_supplements),
            )
            .route(
                "/markers/{slug}/references",
                actix_web::web::get().to(handlers::markers::demo_marker_references),
            ),
    )
    .service(
        actix_web::web::scope("/v1/content")
            .route("/zones", actix_web::web::get().to(handlers::content::zones))
            .route(
                "/markers",
                actix_web::web::get().to(handlers::content::markers),
            )
            .route(
                "/markers/{slug}",
                actix_web::web::get().to(handlers::content::marker_by_slug),
            )
            .route("/tiers", actix_web::web::get().to(handlers::content::tiers))
            .route(
                "/diet-protocols",
                actix_web::web::get().to(handlers::content::diet_protocols),
            )
            .route(
                "/eating-patterns",
                actix_web::web::get().to(handlers::content::eating_patterns),
            )
            .route(
                "/food-categories",
                actix_web::web::get().to(handlers::content::food_categories),
            )
            .route(
                "/medication-categories",
                actix_web::web::get().to(handlers::content::medication_categories),
            )
            .route(
                "/ui-strings",
                actix_web::web::get().to(handlers::content::ui_strings),
            )
            .route(
                "/web",
                actix_web::web::get().to(handlers::web_content::get_all_web_content),
            )
            .route(
                "/web/{page_slug}",
                actix_web::web::get().to(handlers::web_content::get_web_page_content),
            )
            .route(
                "/strings",
                actix_web::web::get().to(handlers::content_strings::get_strings),
            ),
    )
    .service(
        actix_web::web::scope("/admin")
            .route(
                "/dashboard",
                actix_web::web::get().to(handlers::admin::dashboard),
            )
            .route(
                "/services",
                actix_web::web::get().to(handlers::admin_health::service_health),
            )
            .route(
                "/organizations",
                actix_web::web::get().to(handlers::admin_orgs::list_organizations),
            )
            .route(
                "/organizations",
                actix_web::web::post().to(handlers::admin_orgs::create_organization),
            )
            .route(
                "/organizations/{id}",
                actix_web::web::get().to(handlers::admin_orgs::get_organization),
            )
            .route(
                "/organizations/{id}",
                actix_web::web::put().to(handlers::admin_orgs::update_organization),
            )
            .route(
                "/organizations/{id}",
                actix_web::web::delete().to(handlers::admin_orgs::delete_organization),
            )
            .route(
                "/organizations/{id}/delete-preview",
                actix_web::web::get().to(handlers::admin_orgs::delete_preview_organization),
            )
            .route(
                "/organizations/{id}/members",
                actix_web::web::get().to(handlers::admin_orgs::list_org_members),
            )
            .route(
                "/organizations/{id}/license",
                actix_web::web::post().to(handlers::admin_orgs::generate_org_license),
            )
            .route(
                "/organizations/{id}/license/revoke",
                actix_web::web::post().to(handlers::admin_orgs::revoke_org_license),
            )
            .route(
                "/organizations/{id}/license/history",
                actix_web::web::get().to(handlers::admin_orgs::list_org_license_history),
            )
            // Sprint 041 #523 follow-up -- audit log tab
            .route(
                "/organizations/{id}/audit",
                actix_web::web::get().to(handlers::admin_orgs::list_org_audit_log),
            )
            // Sprint 040 #480 -- branding tab
            .route(
                "/organizations/{id}/branding",
                actix_web::web::put().to(handlers::admin_orgs::update_org_branding),
            )
            .route(
                "/organizations/{id}/domains",
                actix_web::web::get().to(handlers::admin_orgs::list_org_domains),
            )
            .route(
                "/organizations/{id}/domains",
                actix_web::web::post().to(handlers::admin_orgs::add_org_domain),
            )
            .route(
                "/organizations/{org_id}/domains/{domain_id}",
                actix_web::web::delete().to(handlers::admin_orgs::delete_org_domain),
            )
            // Sprint 040 #481 -- per-org invoices (Stripe Invoices API)
            .route(
                "/invoice-products",
                actix_web::web::get().to(handlers::admin_org_invoices::list_invoice_products),
            )
            .route(
                "/organizations/{id}/invoices",
                actix_web::web::get().to(handlers::admin_org_invoices::list_org_invoices),
            )
            .route(
                "/organizations/{id}/invoices",
                actix_web::web::post().to(handlers::admin_org_invoices::create_org_invoice),
            )
            .route(
                "/organizations/{org_id}/invoices/{invoice_id}/sync",
                actix_web::web::post().to(handlers::admin_org_invoices::sync_org_invoice_to_stripe),
            )
            .route(
                "/organizations/{org_id}/invoices/{invoice_id}",
                actix_web::web::delete().to(handlers::admin_org_invoices::delete_org_invoice),
            )
            .route(
                "/organizations/{id}/members",
                actix_web::web::post().to(handlers::admin_orgs::add_org_member),
            )
            .route(
                "/organizations/{org_id}/members/{member_id}",
                actix_web::web::put().to(handlers::admin_orgs::update_member_role),
            )
            .route(
                "/organizations/{org_id}/members/{member_id}",
                actix_web::web::delete().to(handlers::admin_orgs::remove_org_member),
            )
            .route(
                "/users",
                actix_web::web::get().to(handlers::admin::list_users),
            )
            // Sprint 040 #482 -- dormant cohort + lifecycle status mutate
            .route(
                "/users/dormant",
                actix_web::web::get().to(handlers::admin::list_dormant_users),
            )
            .route(
                "/users/{id}/lifecycle-status",
                actix_web::web::put().to(handlers::admin::update_user_lifecycle_status),
            )
            .route(
                "/users/{id}/role",
                actix_web::web::put().to(handlers::admin::update_user_role),
            )
            .route(
                "/users/{id}/tier",
                actix_web::web::put().to(handlers::admin::update_user_tier),
            )
            .route(
                "/users/{id}/license",
                actix_web::web::put().to(handlers::admin::update_user_license),
            )
            .route(
                "/email/send",
                actix_web::web::post().to(handlers::admin_email::send_campaign),
            )
            .route(
                "/email/stats",
                actix_web::web::get().to(handlers::admin_email::email_stats),
            )
            // Sprint 040 #476 -- manual lifecycle template send
            .route(
                "/templates/list",
                actix_web::web::get().to(handlers::admin_lifecycle_email::list_templates),
            )
            .route(
                "/templates/send",
                actix_web::web::post().to(handlers::admin_lifecycle_email::send_template),
            )
            // Sprint 040 #479/#483 -- licensing data model read endpoints
            .route(
                "/licensing/feature-registry",
                actix_web::web::get().to(handlers::admin_licensing::list_feature_registry),
            )
            .route(
                "/licensing/tiers",
                actix_web::web::get().to(handlers::admin_licensing::list_tiers),
            )
            .route(
                "/licensing/revocations",
                actix_web::web::get().to(handlers::admin_licensing::list_revocations),
            )
            .route(
                "/licensing/revocations/{jti}/restore",
                actix_web::web::post().to(handlers::admin_licensing::restore_revoked_license),
            )
            .route(
                "/early-access",
                actix_web::web::get().to(handlers::early_access::list_early_access),
            )
            .route(
                "/newsletter/subscribers",
                actix_web::web::get().to(handlers::newsletter::admin_subscribers),
            )
            .route(
                "/newsletter/export",
                actix_web::web::get().to(handlers::newsletter::admin_export),
            )
            .route(
                "/newsletter/sync",
                actix_web::web::post().to(handlers::newsletter::admin_sync),
            )
            // Audit log endpoints
            .route(
                "/audit/access-logs",
                actix_web::web::get().to(handlers::admin_audit::access_logs),
            )
            .route(
                "/audit/events",
                actix_web::web::get().to(handlers::admin_audit::event_logs),
            )
            .route(
                "/audit/stats",
                actix_web::web::get().to(handlers::admin_audit::audit_stats),
            )
            .route(
                "/audit/purge",
                actix_web::web::delete().to(handlers::admin_audit::purge_logs),
            )
            .route(
                "/audit/db-audit",
                actix_web::web::get().to(handlers::admin_audit::db_audit_logs),
            )
            .route(
                "/audit/pgaudit",
                actix_web::web::get().to(handlers::admin_audit::pgaudit_events),
            )
            .route(
                "/contact-submissions",
                actix_web::web::get().to(handlers::contact::admin_list),
            )
            .route(
                "/contact-submissions/{id}/status",
                actix_web::web::put().to(handlers::contact::admin_update_status),
            )
            .route(
                "/content/web-pages",
                actix_web::web::get().to(handlers::web_content::admin_list_web_pages),
            )
            .route(
                "/content/web-pages/{page_id}/sections",
                actix_web::web::post().to(handlers::web_content::admin_add_section),
            )
            .route(
                "/content/web-sections/{section_id}",
                actix_web::web::delete().to(handlers::web_content::admin_delete_section),
            )
            .route(
                "/content/web-sections/{section_id}/translations/{locale}",
                actix_web::web::put().to(handlers::web_content::admin_update_translation),
            )
            .route(
                "/ai-usage",
                actix_web::web::get().to(handlers::admin_ai_usage::get_usage),
            )
            .route(
                "/content-strings",
                actix_web::web::get().to(handlers::content_strings::admin_list),
            )
            .route(
                "/content-strings/export",
                actix_web::web::get().to(handlers::content_strings::admin_export),
            )
            .route(
                "/content-strings",
                actix_web::web::post().to(handlers::content_strings::admin_create),
            )
            .route(
                "/content-strings/{id}",
                actix_web::web::put().to(handlers::content_strings::admin_update),
            )
            .route(
                "/content/translation-status",
                actix_web::web::get().to(handlers::admin_content::translation_status),
            )
            .route(
                "/content/{table}",
                actix_web::web::get().to(handlers::admin_content::list_content),
            )
            .route(
                "/content/{table}/{id}/translations/{locale}",
                actix_web::web::put().to(handlers::admin_content::update_translation),
            )
            .route(
                "/promotions",
                actix_web::web::get().to(handlers::promotions::admin_list),
            )
            .route(
                "/promotions",
                actix_web::web::post().to(handlers::promotions::admin_create),
            )
            .route(
                "/promotions/{id}",
                actix_web::web::put().to(handlers::promotions::admin_update),
            )
            .route(
                "/promotions/{id}",
                actix_web::web::delete().to(handlers::promotions::admin_deactivate),
            )
            .route(
                "/promotions/{id}/redemptions",
                actix_web::web::get().to(handlers::promotions::admin_redemptions),
            )
            .route(
                "/promo/preview",
                actix_web::web::post().to(handlers::promotions::admin_promo_preview),
            )
            .route(
                "/affiliates",
                actix_web::web::get().to(handlers::affiliate::admin_list),
            )
            .route(
                "/affiliates/queue",
                actix_web::web::get().to(handlers::affiliate::admin_queue),
            )
            .route(
                "/affiliates/queue/count",
                actix_web::web::get().to(handlers::affiliate::admin_queue_count),
            )
            .route(
                "/payouts",
                actix_web::web::get().to(handlers::affiliate::admin_list_payouts),
            )
            .route(
                "/conversions/{id}/approve",
                actix_web::web::post().to(handlers::affiliate::admin_approve),
            )
            .route(
                "/conversions/{id}/reject",
                actix_web::web::post().to(handlers::affiliate::admin_reject),
            )
            .route(
                "/payouts/create",
                actix_web::web::post().to(handlers::affiliate::admin_create_payouts),
            )
            .route(
                "/payouts/{id}/mark-paid",
                actix_web::web::post().to(handlers::affiliate::admin_mark_paid),
            )
            .route(
                "/links",
                actix_web::web::get().to(handlers::affiliate::admin_list_links),
            )
            .route(
                "/links/campaign",
                actix_web::web::post().to(handlers::affiliate::admin_create_campaign),
            )
            .route(
                "/settings",
                actix_web::web::get().to(handlers::admin_settings::list_settings),
            )
            .route(
                "/settings/{key}",
                actix_web::web::put().to(handlers::admin_settings::update_setting),
            )
            .route(
                "/debug-whitelist",
                actix_web::web::get().to(handlers::admin_settings::debug_whitelist),
            )
            .route(
                "/features",
                actix_web::web::get().to(handlers::features::admin_list_features),
            )
            .route(
                "/features",
                actix_web::web::post().to(handlers::features::admin_create_feature),
            )
            .route(
                "/features/{id}",
                actix_web::web::put().to(handlers::features::admin_update_feature),
            )
            .route(
                "/features/{id}",
                actix_web::web::delete().to(handlers::features::admin_delete_feature),
            )
            .route(
                "/features/{id}/tiers",
                actix_web::web::put().to(handlers::features::admin_update_tiers),
            )
            .route(
                "/subscriptions/{user_id}/refund",
                actix_web::web::post().to(handlers::billing::admin_refund),
            )
            .route(
                "/refunds",
                actix_web::web::get().to(handlers::billing::admin_refund_list),
            )
            .route(
                "/payments/gateways",
                actix_web::web::get().to(handlers::payment_gateways::admin_list_gateways),
            )
            .route(
                "/payments/gateways/{id}/activate",
                actix_web::web::post().to(handlers::payment_gateways::admin_activate_gateway),
            )
            .route(
                "/payments/gateways/{id}/toggle",
                actix_web::web::post().to(handlers::payment_gateways::admin_toggle_gateway),
            )
            .route(
                "/payments/gateways/{id}/test",
                actix_web::web::post().to(handlers::payment_gateways::admin_test_gateway),
            )
            .route(
                "/publish-website",
                actix_web::web::post().to(handlers::admin_publish::publish_website),
            )
            .route(
                "/backfill-calculated-markers",
                actix_web::web::post().to(handlers::admin::backfill_calculated_markers),
            )
            .route(
                "/affiliate-summary",
                actix_web::web::get().to(handlers::admin::affiliate_summary),
            ),
    )
    .service(actix_web::web::scope("/v1/payments").route(
        "/status",
        actix_web::web::get().to(handlers::payments::payment_status),
    ))
    .service(
        actix_web::web::scope("/api/payments")
            .route(
                "/gateways",
                actix_web::web::get().to(handlers::payment_gateways::public_gateways),
            )
            .route(
                "/preview",
                actix_web::web::post().to(handlers::promotions::payment_preview),
            ),
    )
    .service(actix_web::web::scope("/v1/promotions").route(
        "/validate",
        actix_web::web::post().to(handlers::promotions::validate),
    ))
    .service(actix_web::web::scope("/v1/chat").route(
        "/public",
        actix_web::web::post().to(handlers::public_chat::chat),
    ))
    .service(
        actix_web::web::scope("/api/affiliate")
            .route(
                "/click",
                actix_web::web::post().to(handlers::affiliate::click),
            )
            .route("/me", actix_web::web::get().to(handlers::affiliate::me))
            .route(
                "/me/settings",
                actix_web::web::put().to(handlers::affiliate::update_settings),
            )
            .route(
                "/me/conversions",
                actix_web::web::get().to(handlers::affiliate::my_conversions),
            )
            .route(
                "/me/vanity",
                actix_web::web::put().to(handlers::affiliate::set_vanity),
            )
            .route(
                "/vanity/check",
                actix_web::web::get().to(handlers::affiliate::check_vanity),
            ),
    )
    .service(
        actix_web::web::scope("/api/features")
            .route(
                "",
                actix_web::web::get().to(handlers::features::list_features),
            )
            .route(
                "/stats",
                actix_web::web::get().to(handlers::features::feature_stats),
            ),
    )
    .service(
        actix_web::web::scope("/billing")
            .route(
                "/checkout",
                actix_web::web::post().to(handlers::billing::checkout),
            )
            .route(
                "/portal",
                actix_web::web::get().to(handlers::billing::portal),
            )
            .route(
                "/status",
                actix_web::web::get().to(handlers::billing::status),
            )
            .route("/sync", actix_web::web::post().to(handlers::billing::sync))
            .route(
                "/change-plan",
                actix_web::web::post().to(handlers::billing::change_plan),
            )
            .route(
                "/change-interval",
                actix_web::web::post().to(handlers::billing::change_interval),
            )
            .route(
                "/history",
                actix_web::web::get().to(handlers::billing::payment_history),
            )
            .route(
                "/cancel",
                actix_web::web::post().to(handlers::billing::cancel),
            )
            .route(
                "/reactivate",
                actix_web::web::post().to(handlers::billing::reactivate),
            )
            .route(
                "/webhook",
                actix_web::web::post().to(handlers::billing::webhook),
            )
            // BTC payment routes
            .route(
                "/btc/create-invoice",
                actix_web::web::post().to(handlers::billing_btc::create_invoice),
            )
            .route(
                "/btc/check/{invoice_id}",
                actix_web::web::get().to(handlers::billing_btc::check_invoice),
            )
            .route(
                "/btc/webhook",
                actix_web::web::post().to(handlers::billing_btc::webhook),
            )
            .route(
                "/btc/status",
                actix_web::web::get().to(handlers::billing_btc::btc_status),
            )
            .route(
                "/btc/prices",
                actix_web::web::get().to(handlers::billing_btc::prices),
            ),
    )
    .service(
        actix_web::web::scope("/api/invoices")
            .route(
                "",
                actix_web::web::get().to(handlers::billing::invoices_list),
            )
            .route(
                "/{id}/pdf",
                actix_web::web::get().to(handlers::billing::invoice_pdf),
            ),
    );
}
