-- Populate German translations for food names
-- food_name_de column already exists on marker_foods table

UPDATE marker_foods SET food_name_de = CASE food_name
  WHEN 'Almonds' THEN 'Mandeln'
  WHEN 'Apple Cider Vinegar' THEN 'Apfelessig'
  WHEN 'Apple cider vinegar' THEN 'Apfelessig'
  WHEN 'Apples' THEN 'Äpfel'
  WHEN 'Artichoke' THEN 'Artischocke'
  WHEN 'Aubergine' THEN 'Aubergine'
  WHEN 'Avocado' THEN 'Avocado'
  WHEN 'Bacon' THEN 'Speck'
  WHEN 'Barley' THEN 'Gerste'
  WHEN 'Beef (grass-fed)' THEN 'Rindfleisch (Weidehaltung)'
  WHEN 'Beef liver' THEN 'Rinderleber'
  WHEN 'Beetroot' THEN 'Rote Bete'
  WHEN 'Beets' THEN 'Rote Bete'
  WHEN 'Bell pepper (red)' THEN 'Paprika (rot)'
  WHEN 'Black beans' THEN 'Schwarze Bohnen'
  WHEN 'Blueberries' THEN 'Blaubeeren'
  WHEN 'Bone Broth' THEN 'Knochenbrühe'
  WHEN 'Broccoli' THEN 'Brokkoli'
  WHEN 'Brussels sprouts' THEN 'Rosenkohl'
  WHEN 'Butter' THEN 'Butter'
  WHEN 'Cabbage' THEN 'Kohl'
  WHEN 'Cauliflower' THEN 'Blumenkohl'
  WHEN 'Celery' THEN 'Sellerie'
  WHEN 'Cheese' THEN 'Käse'
  WHEN 'Cherries' THEN 'Kirschen'
  WHEN 'Chia seeds' THEN 'Chiasamen'
  WHEN 'Chicken Breast' THEN 'Hähnchenbrust'
  WHEN 'Chicken Thighs' THEN 'Hähnchenschenkel'
  WHEN 'Chickpeas' THEN 'Kichererbsen'
  WHEN 'Cinnamon' THEN 'Zimt'
  WHEN 'Clams' THEN 'Muscheln'
  WHEN 'Coconut Oil' THEN 'Kokosöl'
  WHEN 'Coconut oil' THEN 'Kokosöl'
  WHEN 'Cod Liver Oil' THEN 'Lebertran'
  WHEN 'Coffee' THEN 'Kaffee'
  WHEN 'Coffee (unsweetened)' THEN 'Kaffee (ungesüßt)'
  WHEN 'Cranberries' THEN 'Preiselbeeren'
  WHEN 'Cream Cheese' THEN 'Frischkäse'
  WHEN 'Cruciferous Vegetables' THEN 'Kreuzblütler-Gemüse'
  WHEN 'Cruciferous vegetables (broccoli, kale)' THEN 'Kreuzblütler (Brokkoli, Grünkohl)'
  WHEN 'Cucumber' THEN 'Gurke'
  WHEN 'Dark Chocolate' THEN 'Dunkle Schokolade'
  WHEN 'Dark chocolate (70%+)' THEN 'Dunkle Schokolade (70%+)'
  WHEN 'Egg whites' THEN 'Eiweiß'
  WHEN 'Egg yolks' THEN 'Eigelb'
  WHEN 'Eggplant' THEN 'Aubergine'
  WHEN 'Eggs' THEN 'Eier'
  WHEN 'Flaxseed' THEN 'Leinsamen'
  WHEN 'Garlic' THEN 'Knoblauch'
  WHEN 'Ghee' THEN 'Ghee'
  WHEN 'Ginger' THEN 'Ingwer'
  WHEN 'Grass-Fed Beef' THEN 'Weiderind'
  WHEN 'Greek yoghurt (plain)' THEN 'Griechischer Joghurt (natur)'
  WHEN 'Green Tea' THEN 'Grüner Tee'
  WHEN 'Green tea' THEN 'Grüner Tee'
  WHEN 'Heavy Cream' THEN 'Sahne'
  WHEN 'Herring' THEN 'Hering'
  WHEN 'Kidney' THEN 'Niere'
  WHEN 'Kidney beans' THEN 'Kidneybohnen'
  WHEN 'Kimchi' THEN 'Kimchi'
  WHEN 'Lamb' THEN 'Lamm'
  WHEN 'Leafy greens' THEN 'Blattgemüse'
  WHEN 'Leafy greens (kale, spinach)' THEN 'Blattgemüse (Grünkohl, Spinat)'
  WHEN 'Lemon' THEN 'Zitrone'
  WHEN 'Lemon Water' THEN 'Zitronenwasser'
  WHEN 'Lentils' THEN 'Linsen'
  WHEN 'Liver' THEN 'Leber'
  WHEN 'Low-fat dairy (milk, yoghurt)' THEN 'Fettarme Milchprodukte (Milch, Joghurt)'
  WHEN 'Macadamia nuts' THEN 'Macadamianüsse'
  WHEN 'Mackerel' THEN 'Makrele'
  WHEN 'Mushrooms (UV-exposed)' THEN 'Pilze (UV-bestrahlt)'
  WHEN 'Mussels' THEN 'Miesmuscheln'
  WHEN 'Oats' THEN 'Haferflocken'
  WHEN 'Oats (rolled)' THEN 'Haferflocken (zart)'
  WHEN 'Olive Oil' THEN 'Olivenöl'
  WHEN 'Olive Oil (extra virgin)' THEN 'Olivenöl (extra vergine)'
  WHEN 'Olive oil (extra virgin)' THEN 'Olivenöl (extra vergine)'
  WHEN 'Oysters' THEN 'Austern'
  WHEN 'Parsley' THEN 'Petersilie'
  WHEN 'Pecans' THEN 'Pekannüsse'
  WHEN 'Pumpkin seeds' THEN 'Kürbiskerne'
  WHEN 'Quinoa' THEN 'Quinoa'
  WHEN 'Red Bell Pepper' THEN 'Rote Paprika'
  WHEN 'Ribeye Steak' THEN 'Ribeye-Steak'
  WHEN 'Salmon' THEN 'Lachs'
  WHEN 'Sardines' THEN 'Sardinen'
  WHEN 'Sauerkraut' THEN 'Sauerkraut'
  WHEN 'Shrimp' THEN 'Garnelen'
  WHEN 'Skinless chicken' THEN 'Hähnchen ohne Haut'
  WHEN 'Spinach' THEN 'Spinat'
  WHEN 'Tart cherries' THEN 'Sauerkirschen'
  WHEN 'Tofu' THEN 'Tofu'
  WHEN 'Turkey' THEN 'Truthahn'
  WHEN 'Turmeric' THEN 'Kurkuma'
  WHEN 'Walnuts' THEN 'Walnüsse'
  ELSE food_name_de
END
WHERE food_name_de IS NULL;
