-- Add display_name and abbreviation columns to markers table
-- display_name: full human-readable name (e.g., "Alkaline Phosphatase")
-- abbreviation: short form (e.g., "ALP")

ALTER TABLE markers ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE markers ADD COLUMN IF NOT EXISTS abbreviation TEXT;

-- Populate display_name and abbreviation for all markers
-- Where marker_name IS the abbreviation, display_name gets the full name
-- Where marker_name IS the full name, abbreviation gets the short form

UPDATE markers SET display_name = CASE marker_slug
  WHEN 'alp' THEN 'Alkaline Phosphatase'
  WHEN 'alt' THEN 'Alanine Aminotransferase'
  WHEN 'ast' THEN 'Aspartate Aminotransferase'
  WHEN 'albumin' THEN 'Albumin'
  WHEN 'apob' THEN 'Apolipoprotein B'
  WHEN 'bp_diastolic' THEN 'Blood Pressure (Diastolic)'
  WHEN 'bp_systolic' THEN 'Blood Pressure (Systolic)'
  WHEN 'basophils_pct' THEN 'Basophils Percentage'
  WHEN 'basophils_abs' THEN 'Basophils Absolute Count'
  WHEN 'bilirubin_direct' THEN 'Direct Bilirubin'
  WHEN 'bilirubin_total' THEN 'Total Bilirubin'
  WHEN 'calcium' THEN 'Calcium'
  WHEN 'creatinine' THEN 'Creatinine'
  WHEN 'cystatin_c' THEN 'Cystatin C'
  WHEN 'dha' THEN 'Docosahexaenoic Acid'
  WHEN 'dheas' THEN 'Dehydroepiandrosterone Sulfate'
  WHEN 'epa' THEN 'Eicosapentaenoic Acid'
  WHEN 'eosinophils_pct' THEN 'Eosinophils Percentage'
  WHEN 'eosinophils_abs' THEN 'Eosinophils Absolute Count'
  WHEN 'estradiol' THEN 'Estradiol'
  WHEN 'fsh' THEN 'Follicle-Stimulating Hormone'
  WHEN 'ferritin' THEN 'Ferritin'
  WHEN 'folate' THEN 'Folate (Vitamin B9)'
  WHEN 'free_androgen_index' THEN 'Free Androgen Index'
  WHEN 'ft3' THEN 'Free Triiodothyronine'
  WHEN 'ft4' THEN 'Free Thyroxine'
  WHEN 'free_testosterone' THEN 'Free Testosterone'
  WHEN 'ggt' THEN 'Gamma-Glutamyl Transferase'
  WHEN 'glucose' THEN 'Blood Glucose'
  WHEN 'hdl_c' THEN 'High-Density Lipoprotein Cholesterol'
  WHEN 'hba1c' THEN 'Glycated Hemoglobin'
  WHEN 'heart_rate' THEN 'Heart Rate'
  WHEN 'hematocrit' THEN 'Hematocrit'
  WHEN 'hemoglobin' THEN 'Hemoglobin'
  WHEN 'holo_tc' THEN 'Holotranscobalamin'
  WHEN 'homocysteine' THEN 'Homocysteine'
  WHEN 'insulin' THEN 'Fasting Insulin'
  WHEN 'iron' THEN 'Serum Iron'
  WHEN 'ketones' THEN 'Blood Ketones (Beta-Hydroxybutyrate)'
  WHEN 'ldh' THEN 'Lactate Dehydrogenase'
  WHEN 'ldl_c' THEN 'Low-Density Lipoprotein Cholesterol'
  WHEN 'lh' THEN 'Luteinizing Hormone'
  WHEN 'lpa' THEN 'Lipoprotein(a)'
  WHEN 'lymphocytes_pct' THEN 'Lymphocytes Percentage'
  WHEN 'lymphocytes_abs' THEN 'Lymphocytes Absolute Count'
  WHEN 'magnesium' THEN 'Magnesium'
  WHEN 'monocytes_pct' THEN 'Monocytes Percentage'
  WHEN 'monocytes_abs' THEN 'Monocytes Absolute Count'
  WHEN 'neutrophils_pct' THEN 'Neutrophils Percentage'
  WHEN 'neutrophils_abs' THEN 'Neutrophils Absolute Count'
  WHEN 'non_hdl_c' THEN 'Non-HDL Cholesterol'
  WHEN 'omega3_index' THEN 'Omega-3 Index'
  WHEN 'phosphate' THEN 'Phosphate'
  WHEN 'platelets' THEN 'Platelets (Thrombocytes)'
  WHEN 'potassium' THEN 'Potassium'
  WHEN 'progesterone' THEN 'Progesterone'
  WHEN 'prolactin' THEN 'Prolactin'
  WHEN 'rbc' THEN 'Red Blood Cell Count'
  WHEN 'shbg' THEN 'Sex Hormone-Binding Globulin'
  WHEN 'selenium' THEN 'Selenium'
  WHEN 'sodium' THEN 'Sodium'
  WHEN 'tsh' THEN 'Thyroid-Stimulating Hormone'
  WHEN 'testosterone' THEN 'Testosterone'
  WHEN 'total_cholesterol' THEN 'Total Cholesterol'
  WHEN 'total_protein' THEN 'Total Protein'
  WHEN 'transferrin' THEN 'Transferrin'
  WHEN 'transferrin_sat' THEN 'Transferrin Saturation'
  WHEN 'triglycerides' THEN 'Triglycerides'
  WHEN 'uric_acid' THEN 'Uric Acid'
  WHEN 'vitamin_a' THEN 'Vitamin A (Retinol)'
  WHEN 'vitamin_b1' THEN 'Vitamin B1 (Thiamine)'
  WHEN 'vitamin_b12' THEN 'Vitamin B12 (Cobalamin)'
  WHEN 'vitamin_b2' THEN 'Vitamin B2 (Riboflavin)'
  WHEN 'vitamin_b3' THEN 'Vitamin B3 (Niacin)'
  WHEN 'vitamin_b5' THEN 'Vitamin B5 (Pantothenic Acid)'
  WHEN 'vitamin_b6' THEN 'Vitamin B6 (Pyridoxine)'
  WHEN 'vitamin_d' THEN 'Vitamin D (25-Hydroxyvitamin D)'
  WHEN 'vitamin_e' THEN 'Vitamin E (Alpha-Tocopherol)'
  WHEN 'wbc' THEN 'White Blood Cell Count'
  WHEN 'waist_circumference' THEN 'Waist Circumference'
  WHEN 'weight' THEN 'Body Weight'
  WHEN 'zinc' THEN 'Zinc'
  WHEN 'egfr' THEN 'Estimated Glomerular Filtration Rate'
  WHEN 'hs_crp' THEN 'High-Sensitivity C-Reactive Protein'
  ELSE marker_name
END,
abbreviation = CASE marker_slug
  WHEN 'alp' THEN 'ALP'
  WHEN 'alt' THEN 'ALT'
  WHEN 'ast' THEN 'AST'
  WHEN 'albumin' THEN 'Alb'
  WHEN 'apob' THEN 'ApoB'
  WHEN 'bp_diastolic' THEN 'Dia'
  WHEN 'bp_systolic' THEN 'Sys'
  WHEN 'basophils_pct' THEN 'Baso%'
  WHEN 'basophils_abs' THEN 'Baso#'
  WHEN 'bilirubin_direct' THEN 'D-Bil'
  WHEN 'bilirubin_total' THEN 'T-Bil'
  WHEN 'calcium' THEN 'Ca'
  WHEN 'creatinine' THEN 'Crea'
  WHEN 'cystatin_c' THEN 'CysC'
  WHEN 'dha' THEN 'DHA'
  WHEN 'dheas' THEN 'DHEA-S'
  WHEN 'epa' THEN 'EPA'
  WHEN 'eosinophils_pct' THEN 'Eos%'
  WHEN 'eosinophils_abs' THEN 'Eos#'
  WHEN 'estradiol' THEN 'E2'
  WHEN 'fsh' THEN 'FSH'
  WHEN 'ferritin' THEN 'Ferr'
  WHEN 'folate' THEN 'B9'
  WHEN 'free_androgen_index' THEN 'FAI'
  WHEN 'ft3' THEN 'fT3'
  WHEN 'ft4' THEN 'fT4'
  WHEN 'free_testosterone' THEN 'fTest'
  WHEN 'ggt' THEN 'GGT'
  WHEN 'glucose' THEN 'Glc'
  WHEN 'hdl_c' THEN 'HDL'
  WHEN 'hba1c' THEN 'HbA1c'
  WHEN 'heart_rate' THEN 'HR'
  WHEN 'hematocrit' THEN 'HCT'
  WHEN 'hemoglobin' THEN 'Hb'
  WHEN 'holo_tc' THEN 'HoloTC'
  WHEN 'homocysteine' THEN 'Hcy'
  WHEN 'insulin' THEN 'Ins'
  WHEN 'iron' THEN 'Fe'
  WHEN 'ketones' THEN 'BHB'
  WHEN 'ldh' THEN 'LDH'
  WHEN 'ldl_c' THEN 'LDL'
  WHEN 'lh' THEN 'LH'
  WHEN 'lpa' THEN 'Lp(a)'
  WHEN 'lymphocytes_pct' THEN 'Lymph%'
  WHEN 'lymphocytes_abs' THEN 'Lymph#'
  WHEN 'magnesium' THEN 'Mg'
  WHEN 'monocytes_pct' THEN 'Mono%'
  WHEN 'monocytes_abs' THEN 'Mono#'
  WHEN 'neutrophils_pct' THEN 'Neut%'
  WHEN 'neutrophils_abs' THEN 'Neut#'
  WHEN 'non_hdl_c' THEN 'Non-HDL'
  WHEN 'omega3_index' THEN 'O3I'
  WHEN 'phosphate' THEN 'PO4'
  WHEN 'platelets' THEN 'PLT'
  WHEN 'potassium' THEN 'K'
  WHEN 'progesterone' THEN 'P4'
  WHEN 'prolactin' THEN 'PRL'
  WHEN 'rbc' THEN 'RBC'
  WHEN 'shbg' THEN 'SHBG'
  WHEN 'selenium' THEN 'Se'
  WHEN 'sodium' THEN 'Na'
  WHEN 'tsh' THEN 'TSH'
  WHEN 'testosterone' THEN 'Test'
  WHEN 'total_cholesterol' THEN 'TC'
  WHEN 'total_protein' THEN 'TP'
  WHEN 'transferrin' THEN 'Tf'
  WHEN 'transferrin_sat' THEN 'TSAT'
  WHEN 'triglycerides' THEN 'TG'
  WHEN 'uric_acid' THEN 'UA'
  WHEN 'vitamin_a' THEN 'VitA'
  WHEN 'vitamin_b1' THEN 'B1'
  WHEN 'vitamin_b12' THEN 'B12'
  WHEN 'vitamin_b2' THEN 'B2'
  WHEN 'vitamin_b3' THEN 'B3'
  WHEN 'vitamin_b5' THEN 'B5'
  WHEN 'vitamin_b6' THEN 'B6'
  WHEN 'vitamin_d' THEN 'VitD'
  WHEN 'vitamin_e' THEN 'VitE'
  WHEN 'wbc' THEN 'WBC'
  WHEN 'waist_circumference' THEN 'Waist'
  WHEN 'weight' THEN 'Wt'
  WHEN 'zinc' THEN 'Zn'
  WHEN 'egfr' THEN 'eGFR'
  WHEN 'hs_crp' THEN 'hsCRP'
  ELSE marker_name
END;
